name = "UTest"
uuid = "df77154b-9e5d-4695-9e78-90260a8880a4"
authors = ["Jürgen Fuhrmann <juergen-fuhrmann@web.de>"]
version = "0.1.0"

[deps]
PhysicalConstants = "5ad8b20f-a522-5ce9-bfc9-ddf1d5bda6ab"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"
